#!/usr/bin/env bash

set -e

bundle install --path "${BUNDLE_PATH:-.gems}"
bundle exec rspec spec/lambdarunner_runner_spec.rb
bundle exec rspec spec/lambdarunner_events_spec.rb

npm --prefix js install
npm --prefix js run test
